config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#all_post'
  devise_for :users
  resources :topics do
    resources :posts
  end
  get "/users/edit", to: "users#edit", as: "edit_user"
  patch "/users", to: "users#update", as: "user"
  post '/topics/:topic_id/posts/:post_id/comments', to: 'comment#create', as: 'topic_post_comments'
  post '/topics/:topic_id/posts/:post_id/ratings', to: 'rating#create', as: 'topic_post_ratings'
  get '/topics/:topic_id/posts/:post_id/comments/edit/:id', to: 'comment#edit', as: 'edit_topic_post_comment'
  put '/topics/:topic_id/posts/:post_id/comments/:id', to: 'comment#update', as: 'topic_post_comment'
  delete '/topics/:topic_id/posts/:post_id/comments/:id', to: 'comment#delete', as: 'topic_post_comment_delete'
  post '/topics/:topic_id/posts/:post_id/comment_rating/:id', to: 'comment#comment_rating', as: 'topic_post_comment_rating'
  get 'topic/:topic_id/posts/:post_id/comment_users/:id', to: 'comment#show', as: 'show_rating'
  post 'topics/:topic_id/posts/:id/read_post', to: 'posts#read_post' , as: 'read_post'
  get '/posts', to: 'posts#all_post', as: 'all_post'
  get '/posts/all', to: 'posts#posts', as: 'posts'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1 or /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url, notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:name, :description)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<div class="container-fluid" >
 <style>
     .width{
  width: 30%;
  }
</style>
  <%= form_with(model: topic) do |form| %>
    <% if topic.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

        <ul>
          <% topic.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= form.label :name %><br>
      <%= form.text_field :name, class: "form-control width" %>
    </div>

    <div class="field">
      <%= form.label :description %><br>
      <%= form.text_field :description, class: "form-control width"  %>
    </div>
<br>
    <div class="actions">
      <%= form.submit "Submit", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>
<br>
<div class="mx-3">
<%= link_to 'Show', @topic, class:"btn btn-secondary" %>
<%= link_to 'Back', topics_path, class:"btn btn-secondary" %>
</div>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid mr-4">
<h1>Topics</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= topic.description %></td>
        <td><%= link_to 'Show', topic , class: "btn btn-secondary"%></td>
        <td><%= link_to 'Edit', edit_topic_path(topic), class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger"%></td>
        <td><%= link_to "#{topic.name} posts", topic_posts_path(topic), class: "btn btn-secondary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path, class: "btn btn-secondary" %>
<%= link_to 'All Posts', all_post_path, class: "btn btn-secondary" %></div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>
<br>
<%= link_to 'Back', topics_path, class: "btn btn-secondary mx-3 text-white" %>

app/views/topics/show.html.erb
<div class="container mt-5"><p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @topic.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @topic.description %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic), class: "btn btn-primary"%>
<%= link_to 'Back', topics_path, class: "btn btn-secondary" %></div>