config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#all_post'
  devise_for :users
  resources :topics do
    resources :posts
  end
  get "/users/edit", to: "users#edit", as: "edit_user"
  patch "/users", to: "users#update", as: "user"
  post '/topics/:topic_id/posts/:post_id/comments', to: 'comment#create', as: 'topic_post_comments'
  post '/topics/:topic_id/posts/:post_id/ratings', to: 'rating#create', as: 'topic_post_ratings'
  get '/topics/:topic_id/posts/:post_id/comments/edit/:id', to: 'comment#edit', as: 'edit_topic_post_comment'
  put '/topics/:topic_id/posts/:post_id/comments/:id', to: 'comment#update', as: 'topic_post_comment'
  delete '/topics/:topic_id/posts/:post_id/comments/:id', to: 'comment#delete', as: 'topic_post_comment_delete'
  post '/topics/:topic_id/posts/:post_id/comment_rating/:id', to: 'comment#comment_rating', as: 'topic_post_comment_rating'
  get 'topic/:topic_id/posts/:post_id/comment_users/:id', to: 'comment#show', as: 'show_rating'
  post 'topics/:topic_id/posts/:id/read_post', to: 'posts#read_post' , as: 'read_post'
  get '/posts', to: 'posts#all_post', as: 'all_post'
  get '/posts/all', to: 'posts#posts', as: 'posts'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  scope :between_dates, -> (from_date, to_date) {
    from_date = from_date.to_date
    to_date = to_date.to_date.tomorrow
    where(created_at: from_date..to_date)
  }

  belongs_to :topic
  has_many :comments,dependent: :destroy, counter_cache: :comments_count
  has_and_belongs_to_many :tags
  accepts_nested_attributes_for :tags
  has_many :ratings, dependent: :destroy, counter_cache: :ratings_count
  has_one_attached :image
  has_and_belongs_to_many :users,join_table: :posts_users
  validates :title, length: { maximum: 20 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :set_topic, except: %i[ all_post posts]

  load_and_authorize_resource
  def all_post
        if params[:from_date] && params[:to_date] && ( params[:from_date].present? || params[:to_date].present?)

          @posts = Post.between_dates(params[:from_date], params[:to_date])
        else
          to_date = Date.today
          from_date = 1.day.ago.to_date
          @posts = Post.between_dates(from_date, to_date)
        end

        @all_posts = @posts.paginate(page: params[:page], per_page: 10)
  end

  def posts
    @all_posts = Post.paginate(page: params[:page], per_page:10)
  end


  # GET /posts or /posts.json
  def index
    @posts = @topic.posts
    @status = @posts.map do |post|
      post.users.exists?(id: current_user.id) ? 'Read' : 'Unread'
    end

  end


  # GET /posts/1 or /posts/1.json
  def show
    @comment = Comment.new
    @comments = @post.comments
    @tags = @post.tags
    @rating = Rating.new
    @commentrating = Commentrating.new
    @select = @post.ratings.where(user_id: current_user.id)
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.tags.build
    @all_tags = Tag.all
  end



  # GET /posts/1/edit
  def edit

    @tag = @post.tags.pluck(:hashtag)
    @tag_name = @tag.join(" ")
    @all_tags = Tag.all
  end

  def read_post
    @check = @post.users.exists?(id: current_user.id)
    if  @check

    else
      @post.users << current_user

    end
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.topic_id = @topic.id
    @post.user_id = current_user.id
    tag_array = tag_params
    temp = tag_array[:tags_attributes]
    tags = temp[:hashtag].split(" ")
    tags.each do |t|
      tag = Tag.find_by_hashtag(t)
      if tag.present?
        @post.tags << tag
      else
        tag = Tag.new(hashtag: t)
        if tag.save
          @post.tags << tag
        end
      end
      end

    respond_to do |format|
      if @post.save
        format.js
        format.json { render :show, status: :created, location: @post }
      else
        format.js
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        tag_array = tag_params
        @post.tags.clear
        temp = tag_array[:tags_attributes]
        tags = temp[:hashtag].split(" ")
        tags.each do |t|
          tag = Tag.find_by_hashtag(t)
          if tag.present?
            @post.tags << tag
          else
            tag = Tag.new(hashtag: t)
            if tag.save
              @post.tags << tag
            end
          end
        end
        format.html { redirect_to topic_post_path(@topic, @post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to topic_posts_path(@topic), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

  def set_topic
    begin
      @topic = Topic.find(params[:topic_id])
    rescue
      redirect_to all_post_path
    end
  end


    def post_params
      params.require(:post).permit(:title, :description, :image)
    end

  def tag_params
    params.require(:post).permit(tags_attributes: [:hashtag])
  end



end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_error.js.erb
<% if post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
      <% post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/posts/_form.html.erb
<head>
  <%= javascript_pack_tag 'form', 'data-turbolinks-track': 'reload', defer: true %>
</head>
<style>
    .width{
        width: 30%;
    }
</style>
<div class="container-fluid" >
<div class="loading-screen">
  <div class="loading-spinner"></div>
  <div class="loading-text">Loading...</div>
</div>
<%= form_with(model: [@topic, post], local: false, id: 'form') do |form| %>

    <div id="error-container">
    </div>


  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control width" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control width" %>
  </div><br>
    <div class="mb-3" style="width: 16%">
      <%= form.label :image, class: "form-label" %>
      <%= form.file_field :image, class: "form-control" %>
    </div>

    <%= form.fields_for :tags_attributes do |tag| %>
      <%= tag.label :Hashtag %>   <div style="display: flex">
      <%= tag.text_area :hashtag, id: :tags, placeholder: "Enter tags with space", value: @tag_name, class: "form-control width", style: " margin-right: 2%" %><br>

      <div class="form-floating" style="width: 10%">
        <select class="form-select" id="myselect" onchange="myFunction()">
          <option>select tag</option>
          <% @all_tags.each do |tag| %>
            <option value="<%= tag.hashtag %>"><%= tag.hashtag %></option>
          <% end %>
        </select>
        <label for="myselect">Select Tag</label>
      </div>
</div>
  <% end %>

  <div class="actions"><br>
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

<style>

    .loading-screen {

        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 9999;
        background-color: rgba(255, 255, 255, 0.5);
        display: none;
        justify-content: center;
        align-items: center;
    }

    .loading-spinner {
        border-radius: 50%;
        width: 2em;
        height: 2em;
        margin-right: 10px;
        border: 5px solid rgba(0, 0, 0, 0.1);
        border-top-color: #3498db;
        animation: spin 1s infinite linear;
    }

    @keyframes spin {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }

    .loading-text {
        font-size: 1.2em;
        color: #333;
    }

</style>
<script>
    function myFunction() {
        var a = $('#myselect').val();
        var value = $('#tags').val();
        if (value == "") {
            value = value + a;
        } else {
            value = value + " " + a;
        }
        $('#tags').val(value);
    }


    $(document).ready(function() {
        $('#form').on('submit', function() {
            $('.loading-screen').css('display', 'flex');
        });
    });

</script>
</div>

app/views/posts/all_post.html.erb
<div class="m-4"><%= link_to 'Topics', topics_path, class: "btn btn-primary" %>  <%= link_to 'All Posts', posts_path, class: "btn btn-secondary" %>
</div>
<%= form_with url:all_post_path, method: :get do |form| %>
  <div class="row g-2 align-items-center">
    <div class="col-auto">
      <%= form.label :from_date, "From Date:", class: "col-form-label" %>
    </div>
    <div class="col-auto">
      <%= form.date_field :from_date, class: "form-control", required: true %>
    </div>
    <div class="col-auto">
      <%= form.label :to_date, "To Date:", class: "col-form-label" %>
    </div>
    <div class="col-auto">
      <%= form.date_field :to_date, class: "form-control", required: true %>
    </div>
    <div class="col-auto">
      <%= form.submit("show details", class: "btn btn-primary") %>
    </div>
  </div>
<% end %>
<br>
<% if @all_posts.present? %>
  <% @all_posts.each do |post| %>
    <div class="container">
      <h3 class="py-3"><%= post.title.upcase %></h3><br>
      <% if post.image.present? %>
        <%= image_tag(post.image, class: "img-fluid rounded image py-3") %>
      <% end %><br>
      <div class="content py-3"> <%= post.description %></div>
    </div><br>
  <%end %>
  <nav class="mt-4" aria-label="Page navigation">
    <%= will_paginate @all_posts, previous_label: 'Previous', next_label: 'Next', class: 'pagination justify-content-center' %>
  </nav>
<% end %>

<style>

    h3 {
        margin-bottom: -1.5em;
    }
    .image {
        width: 50%;
        height: 40%;
        margin-left: 25%;
    }

    .container{
        border: 1px solid black;
        width: 60%;
        height: 45%;
        padding: 2%;
        border-radius: 6px;
    }

</style>

app/views/posts/create.js.erb
$('.loading-screen').css('display', 'none');
<% if @post.persisted? %>
alert('Your post was created successfully!');
$('#form')[0].reset();

$('#error-container').html('');
<% else %>
$('#error-container').html('<%= j render "posts/error", post: @post %>');
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>
<br>
<div class="mx-3">
<%= link_to 'Show', topic_post_path(@topic, @post), class:"btn btn-secondary" %>
<%= link_to 'Back', topic_posts_path(@topic), class: "btn btn-secondary" %>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid mr-4">
<h1>Posts</h1>

  <table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Topic</th>
      <th colspan="3"></th>
      <th></th>
    </tr>
  </thead>

  <tbody><% i=0 %>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= @topic.name %></td>
        <td><%= link_to 'Show', topic_post_path(@topic, post), class: "btn btn-secondary" %></td><% if can? :update, post %>
        <td><%= link_to 'Edit', edit_topic_post_path(@topic, post), class: "btn btn-primary" %></td><% else %><td></td><% end %> <% if can? :destroy, post %>
        <td><%= link_to 'Destroy', topic_post_path(@topic, post), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td> <% else %><td></td> <% end %>
          <td><h6> <% if @status[i] == 'Read'%>
              <em style="color: blueviolet">READ</em>
            <%else%>
              <em style="color: blue">UNREAD</em>
            <% end %>
          </h6></td>
          <%i+=1 %>
    </tr>
    <% end %>
  </tbody>
  </table>


<br>

<%= link_to 'New Post', new_topic_post_path, class: "btn btn-secondary" %>    <%= link_to 'Back', topics_path, class: "btn btn-secondary" %></div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>
<br>
<%= link_to 'Back', topic_posts_path(@topic), class: "btn btn-secondary mx-3" %>

app/views/posts/posts.html.erb
<div class="m-4"><%= link_to 'Topics', topics_path, class: "btn btn-primary" %>  <%= link_to 'All Posts', posts_path, class: "btn btn-secondary" %>
</div>
<%= form_with url:all_post_path, method: :get do |form| %>
  <div class="row g-2 align-items-center">
    <div class="col-auto">
      <%= form.label :from_date, "From Date:", class: "col-form-label" %>
    </div>
    <div class="col-auto">
      <%= form.date_field :from_date, class: "form-control", required: true %>
    </div>
    <div class="col-auto">
      <%= form.label :to_date, "To Date:", class: "col-form-label" %>
    </div>
    <div class="col-auto">
      <%= form.date_field :to_date, class: "form-control", required: true %>
    </div>
    <div class="col-auto">
      <%= form.submit("show details", class: "btn btn-primary") %>
    </div>
  </div>
<% end %>
<br>
<% if @all_posts.present? %>
  <% @all_posts.each do |post| %>
    <div class="container">
      <h3 class="py-3"><%= post.title.upcase %></h3><br>
      <% if post.image.present? %>
        <%= image_tag(post.image, class: "img-fluid rounded image py-3") %>
      <% end %><br>
      <div class="content py-3"> <%= post.description %></div>
    </div><br>
  <%end %>
  <nav class="mt-4" aria-label="Page navigation">
    <%= will_paginate @all_posts, previous_label: 'Previous', next_label: 'Next', class: 'pagination justify-content-center' %>
  </nav>
<% end %>

<style>

    h3 {
        margin-bottom: -1.5em;
    }
    .image {
        width: 50%;
        height: 40%;
        margin-left: 25%;
    }

    .container{
        border: 1px solid black;
        width: 60%;
        height: 45%;
        padding: 2%;
        border-radius: 6px;
    }

</style>

app/views/posts/rating_show.html.erb
<% @users.each do |user| %>
  <br><%= user.email %>
<% end %><br>
<%= link_to 'Back', topic_post_path(@topic, @post) %>

app/views/posts/show.html.erb
<head>
    <%= javascript_pack_tag 'post', 'data-turbolinks-track': 'reload', defer: true %>
</head>
<div class="container">
  <h1><%= @post.title.upcase %></h1>
  <p><%= @post.description %></p>
  <p><strong>Topic:</strong> <%= @topic.name %></p>

  <div class="mb-3">
    <% if @post.image.present? %>
      <%= image_tag(@post.image, class: "img-fluid", width: "50%", height: "25%") %>
    <% end %>
  </div>


  <div class="mb-3">
    <% @tags.each do |tag| %>
      <span class="badge bg-primary"><%= tag.hashtag %></span>
    <% end %>
  </div>

  <div class="mb-3">
    <p>Total Ratings: <%= @post.ratings_count || 0 %></p>
    <p>Average Ratings: <%= @post.average_rating || 0 %></p>
  </div>

  <%= form_with model: @rating, id: "form", url: topic_post_ratings_path(@topic, @post), method: :post do |r| %>
    <div class="mb-3">
      <%= r.label :Ratings %><br>
      <% [1, 2, 3, 4, 5].each do |value| %>

        <% checked = @select.any? { |rating| rating.rating.to_s == value.to_s } %>

        <%= r.radio_button :rating, value.to_s, checked: checked, id: (checked ? "checked" : nil), class: "rating-radio form-check-input" %>
        <%= label_tag "rating-#{value}", value, class: "rating-label" %>

      <% end %>

    </div>
  <% end %><br>

  <div class="mb-3">
    <% if can? :update, @post %>
      <%= link_to 'Edit', edit_topic_post_path(@topic, @post), class: "btn btn-primary" %>
    <% end %>
    <%= link_to 'Back', topic_posts_path(@topic), class: "btn btn-secondary" %>
  </div>

  <%= form_with model: @comment, url: topic_post_comments_path(@topic, @post),local: false , method: :post do |f|%>
    <div class="mb-3">
      <%= f.label :comment, class: "form-label" %>
      <%= f.text_area :comment, class: "form-control my-2" %>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
  <% end %>
  <div style="display: none"><div id = "post"><%= @post.id %></div><div id= "topic"><%= @topic.id %></div></div>
  <div class="mb-3">
    <p>Total Comments: <%=  @post.comments_count || 0  %></p>
    <% @comments.each do |comment| %><div class="comment">
    <div class="view">
      <div  class="box border p-3 mb-3">
        <div class="px-5 py-3 container my-2", style="display: inline-block; margin: auto; border-radius: 4px; background: #efefef"><%= comment.comment %></div><br>
        <div class="my-2">
          <% if can? :update, comment %>
            <button class="edit-button btn btn-sm btn-primary">Edit</button>
          <% end %>
          <% if can? :delete, comment %>
            <%= link_to 'Delete', topic_post_comment_delete_path(@topic, @post, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
          <% end %>
        </div>
        <%= form_with model: @commentrating, url: topic_post_comment_rating_path(@topic, @post, comment), method: :post do |r| %>
          <div class="mb-3">
            <% [1, 2, 3, 4, 5].each do |value| %>
              <%= r.radio_button :rating, value.to_s, class: "rating-radio form-check-input" %>
              <%= label_tag "rating-#{value}", value, class: "rating-label" %>
            <% end %>
          </div>
        <% end %><br>
      </div>
    </div>
    <% if can? :update, comment %>
    <div class="edit " style="display: none">
      <%= form_with model: @comment, url: topic_post_comment_path(@topic, @post, comment), local: false, method: :put do |f| %>
        <div class="mb-3">
          <%= f.label :comment, class: "form-label" %>
          <%= f.text_area :comment, class: "form-control my-2", value: comment.comment %>
          <%= f.submit "Submit", class: "btn btn-sm btn-primary" %>
          <button class="back-button btn btn-sm btn-secondary">Back</button>
        </div>
      <% end %>
    </div>
  </div><% end %>
<% end %></div> </div>
<script>



    // function Rating() {
    //     document.getElementById("form").submit();
    // }

    // $(document).ready(function() {
    //     $("#form1").on("click", function() {
    //         this.submit();
    //     });
    // });
    $(document).ready(function() {
        const post = $('#post').text().trim();
        const topic = $('#topic').text().trim();
        $.ajax({
            type: 'POST',
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            url: 'http://127.0.0.1:3000/topics/' + topic + '/posts/' + post + '/read_post',
        });
    });
    $(document).ready(function() {
        $("#checked").on("click", function() {
            this.value = 0;
            $("#form").submit();
        });
    });

    $(document).ready(function() {
        $('.edit-button').click(function() {
            var $comment = $(this).closest('.comment');
            $(this).parent().parent().hide();
            $comment.find('.edit').show();
        });
        $('.back-button').click(function() {
            $(this).parent().parent().hide();
            $(this).parent().parent().prev('.view').show();
        });
    });

    const radioButtons = document.querySelectorAll('input[type="radio"]');
    radioButtons.forEach(radioButton => {
        radioButton.addEventListener('click', () => {
            const form = radioButton.closest('form');
            form.submit();
        });
    });


</script>
<style>
    .box {
        border: 1px solid black;
        padding: 15px;
        overflow-wrap: break-word;
    }
    .rating-radio:focus {
        outline: none;
        box-shadow: none;
    }

</style>